spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  messages:
    basename: messages, errors
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9c7b659052a5c2efddde496667f27ec1
            client-secret: tmaKzyjSen95EkroHMn9AMEpOvKr3bkl
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  profiles:
    active: prod


decorator:
  datasource:
    p6spy:
      enable-logging: false
---
spring:
  config:
    activate:
      on-profile: prod

  datasource :
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

cloud:
  aws:
    s3:
      bucket: ${bucket_name}
      url: ${AWS_S3_URL}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}


project:
  url: ${AWS_URL}
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true
    username: infbook
    password: dev

  devtools:
    livereload:
      enabled: true
    restart:
      exclude: static/img/items/**
      enabled: false

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/mysql/schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    #generate-ddl: false
    #defer-datasource-initialization: true #하이버네이트


  h2:
    console:
      enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
cloud:
  aws:
    s3:
      bucket: ${bucket.name}
      url: ${AWS_S3_URL}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

project:
  url: http://localhost:8080/

#file:
#  dir: /Users/choedonghyeon/Desktop/Spring-Infbook/src/main/resources/static/img/items/